name: Build the android APK
permissions:
  contents: read
on:
  push:
    branches:
      - main
      - prod

  workflow_dispatch:
    inputs:
      build_type:
        description: "Which build type to use for the APK"
        required: true
        default: "release"
        type: choice
        options:
          - release
          - debug
          - diagnostic

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAIN_PROJECT_MODULE: app
  APK_FILE_NAME: UmihiMusic
  STORE_FILE: release-key.jks
  BETA_TAG: beta

jobs:
  build-android-apk:
    if: github.repository == 'ilianoKokoro/umihi-music'
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set Up JDK
        uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > ${{env.MAIN_PROJECT_MODULE}}/${{ env.STORE_FILE }}
        env:
          KEYSTORE_BASE64: ${{ secrets.SIGNING_KEY }}

      - name: Create keystore.properties file
        run: |
          echo "storeFile=${{ env.STORE_FILE }}" > keystore.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Run tests
        run: ./gradlew test

      - name: Build APKs
        env:
          build_type: ${{ inputs.build_type || 'release' }}
        run: |
          case "$build_type" in
            debug)
              GRADLE_VARIANT="Debug"
              ;;
            diagnostic)
              GRADLE_VARIANT="Diagnostic"
              ;;
            *)
              GRADLE_VARIANT="Release"
              ;;
          esac

          if [[ "${{ github.ref_name }}" == "prod" ]]; then
            ./gradlew \
              assembleStandalone${GRADLE_VARIANT} \
              assembleStore${GRADLE_VARIANT} \
              -Pbeta=false \
              -PgitHash=${{ github.sha }}
          else
            ./gradlew \
              assembleStandalone${GRADLE_VARIANT} \
              -Pbeta=true \
              -PgitHash=${{ github.sha }}
          fi

      - name: Collect APKs
        env:
          build_type: ${{ inputs.build_type || 'release' }}
        run: |
          mkdir -p release-apks

          cp app/build/outputs/apk/standalone/$build_type/${{env.APK_FILE_NAME}}.apk \
            release-apks/${{env.APK_FILE_NAME}}.apk

          if [[ "${{ github.ref_name }}" == "prod" ]]; then
            cp app/build/outputs/apk/store/$build_type/${{env.APK_FILE_NAME}}-store.apk \
              release-apks/${{env.APK_FILE_NAME}}-store.apk
          fi

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: apk-files
          path: release-apks/
          overwrite: true
          if-no-files-found: error
  update-beta-prerelease:
    permissions:
      packages: write
      contents: write
    if: github.ref_name != 'prod' && (github.event_name != 'workflow_dispatch' || inputs.build_type == 'release')
    needs:
      - build-android-apk
    runs-on: ubuntu-latest
    name: Update the beta GitHub release
    steps:
      - uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts

      - name: Delete Old Beta Release
        run: gh release delete ${{ env.BETA_TAG }} --cleanup-tag -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new Beta release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.BETA_TAG }}
          name: Beta
          artifacts: ./artifacts/**/*.apk
          allowUpdates: true
          removeArtifacts: true
          generateReleaseNotes: false
          body: ${{ github.event.head_commit.message }}
          makeLatest: false
          prerelease: true
          draft: false
          commit: ${{ github.sha }}

  publish-github-release:
    permissions:
      packages: write
      contents: write
    if: github.ref_name == 'prod' && (github.event_name != 'workflow_dispatch' || inputs.build_type == 'release')
    needs:
      - build-android-apk
    runs-on: ubuntu-latest
    name: Publish the GitHub release
    steps:
      - uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
      - name: Extract version
        id: get_version
        run: |
          version=$(grep -oP 'val\s+appVersionName\s*=\s*"\K[^"]+' app/build.gradle.kts)

          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create a Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.get_version.outputs.version }}
          commit: prod
          artifacts: ./artifacts/**/*.apk
          generateReleaseNotes: false
          draft: true
          body: |
            ## Release v${{ steps.get_version.outputs.version }}

            ### Features
            -

            ### Bug fixes
            -

            ### Full Changelog
            https://github.com/ilianoKokoro/umihi-music/compare/v${{ steps.get_version.outputs.version }}...v${{ steps.get_version.outputs.version }}

            ## FAQ
            ### What is the difference between the normal APK and the `store` apk and which one should I download ?
            _The `store` version is the app version that is hosted on `F-droid` and has the updater removed. If you download the app directly from GitHub, download the normal version._
